influxdb:
  build: .
  ports:
    - "8083:8083"
    - "8086:8086"

telegrafbuild:
  build: ./docker_build_telegraph
  volumes:
    - ./docker_build_telegraph/src:/go
    #- ./docker_build_telegraph/src/:/go/src/github.com/influxdb/telegraf
  links:
    - influxdb
