influxdb:
  build: .
  ports:
    - "8083:8083"
    - "8086:8086"

telegrafbuild:
  build: ./docker_build_telegraf
  volumes:
    - ./docker_build_telegraf/src:/go
    - ./docker_build_telegraf/telegraf.conf:/etc/opt/telegraf/telegraf.conf
  links:
    - influxdb
